name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Режим: проверять только явно включенные языки
          VALIDATE_ALL_CODEBASE: false
          
          # ✅ ВКЛЮЧАЕМ (Оставляем только true)
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_CPP: true
          
          # ❌ ВЫКЛЮЧАЕМ (Полностью удалите или закомментируйте строки с =false)
          # Не пишите здесь VALIDATE_PYTHON_PYLINT: false
          # Просто не указывайте этот язык, и он не будет проверяться
